######################################################################
##
## Filename: OPP_tb.udo
## Created on: Mon Mar 25 1:20:53 PM Eastern Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
