######################################################################
##
## Filename: top_tb.udo
## Created on: Mon Mar 25 12:23:18 PM Eastern Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
